### ISSUE TITLE
Feature Request: Allow for adjustment of replay rate

### ISSUE THREAD

**Issue by jameswahlin** [ParsePlatform/flashback#10]
When load testing a database cluster it is important to determine to what degree your current system can scale. The current "real" mode is useful, but I would love to see the ability to replay real traffic with a replay rate multiplier. 

If I expect for example that my production traffic is going to triple over the next 12 months, I would like to run current production load first at 3 times the current rate to confirm we can handle. I would then scale that up to the point where performance is no longer acceptable to understand where the breaking point is.

**Comment by tredman** [comment]
This was added in this diff - see the 'speedup' flag: https://github.com/ParsePlatform/flashback/commit/da16b6e48512298fb82d24f12e01b6603b0dafad#diff-3de618ea8687f44a8712bcc493164267R88
