### ISSUE TITLE
pcap_converter: add mongoproto.OpDelete, mongoproto.OpUpdate and mongoproto.OpGetMore operations once available

### ISSUE THREAD

**Issue by timvaillancourt** [ParsePlatform/flashback#40]
Delete, Update and GetMore operations don't work with pcap_converter because github.com/tmc/mongoproto does not have a complete set of methods _(.FromReader(), .OpCode() and .String())_ for these types.

I've started to fix this on tmc/mongoproto on this branch of mongoproto: https://github.com/timvaillancourt/mongoproto/tree/update_delete_fromreaders.

This issue is a placeholder to remind me (or someone) to add Delete, Update and GetMore (if that's even possible) to pcap_converter once tmc/mongoproto supports it.

**Comment by tmc** [comment]
@timvaillancourt please do submit PRs on that other repo

**Comment by timvaillancourt** [comment]
Sure thing @tmc. I'll finish drafting it up and I might bug you for some ideas later - I got some code started but for some reason I couldn't get valid bson out of the update/delete packets. I think there is just more data in the payload I'm not reading but we'll see.

**Comment by timvaillancourt** [comment]
Update: A PR to support opUpdate and opDelete is ready at https://github.com/tmc/mongoproto/pull/1.
